import type { NextPage } from 'next';
import Head from 'next/head';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>YC WhatsApp</title>
        <meta name="description" content="Generated by Yuiichan" />
      </Head>

      <Sidebar />
    </div>
  );
};

export default Home;
